<section>
	<div class="home-description">
		<h2>Discover unique vector graphics and stock illustrations</h2>
		<h3>Enhance your ideas with illustrations, vector images, graphics and clipart</h3>
	</div>
</section>

<section>
	<div class="home-hero-banner">

	</div>
</section>

<?php echo $this->getChildHtml('product.popular') ?>

<section>
	<div class="home-welcome">
		<p>Welcome to the Create Adrenaline! We make digital artwork and designs for Graphic Designers, Photoshop Masters, and Illustrator Pros, we’ve got vectors, line art, t-shirt designs, and more.</p>
		<p>If you need help getting something you find here printed we recommend the checking out our custom printing partners below.</p>
	</div>
</section>

<section>
	<div class="featured-partners">
		<h2><?php echo $this->__('Custom Printing Partners') ?></h2>
		<div class="columns">
			<div class="columns_d1of3 partner">
				<a href="http://stickerrobot.com">
					<img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/partners/sr_280x180.gif" alt="Sticker Robot Custom Sticker Printing" class="printer-logo" />
				</a>
			</div>
			<div class="columns_d1of3 partner">
				<a href="http://threadbird.com/">
					<img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/partners/tb_280x180.gif" alt="Threadbird Custom Apparel Printing" class="printer-logo" />
				</a>
			</div>
		</div>
	</div>
</section>