<section>

	<div class="block-about">

		<div class="block-about_header">
			<h2>Unique clip art, custom t-shirt designs and illustrations.</h2>
			<h2>Fast, professional, and easy-to-use.</h2>
		</div>

		<div class="block-about_actions">
			<button type="button" id="trigger-overlay" class="button"><span><span>Learn More</span></span></button>
		</div>

	</div>

</section>

<?php echo $this->getChildHtml('product.popular') ?>

<section>

	<div class="col3-set featured-partners">

		<h2><?php echo $this->__('Custom Printing Partners') ?></h2>

		<div class="col-1 item partner first">

			<a href="http://stickerrobot.com">
				<img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/partners/sr_280x180.gif" alt="Sticker Robot Custom Sticker Printing" class="printer-logo" />
			</a>

		</div>

		<div class="col-2 item partner">

			<a href="http://threadbird.com/">
				<img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/partners/tb_280x180.gif" alt="Threadbird Custom Apparel Printing" class="printer-logo" />
			</a>

		</div>

		<div class="col-3 item partner last">
		</div>

	</div>

</section>

<section>

	<div class="overlay overlay-cornershape" data-path-to="m 0,0 1439.999975,0 0,805.99999 -1439.999975,0 z">

		<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1440 806" preserveAspectRatio="none">
			<path class="overlay-path" d="m 0,0 1439.999975,0 0,805.99999 0,-805.99999 z"/>
		</svg>

		<button type="button" class="overlay-close">Close</button>

		<div>

			<div>

				<h3>About Create Adrenaline</h3>

				<p>The Create Adrenaline Design site is an online portal offering unique, hand made, digital designs from various artists.</p>
				<p>Anyone looking for a quick low cost design solution, or an easy DIY project can download these professional vector, illustration, and clip art files, and then modify using an Adobe Creative Suite application, or by contacting one of our partner vendors, who will help you build and print your design.</p>

				<ul>
					<li><a href="/printers" class="button"><span><span>View Featured Printers</span></span></a></li>
					<li><a href="/contacts" class="button"><span><span>Ask A Question</span></span></a></li>
				</ul>

			</div>

		</div>

	</div>

</section>